export {
    gameStart,
    gameFinished,
    boxClicked,
    nextLvl,
    timerTick,
    storeNewData,
    submitNewPlayer,
    selectPlayer,
    selectLevel,
    deletePlayer,
    checkGameData,
    storeGameData,
    switchLvl,
    switchPlayer,
    invalidUsername,
    retryUsername,
    showTopScores,
    showCharts,
    hideChart
} from './actions';
